"""Generated gRPC/protobuf stubs for the frozen ``ecosys.v1`` contract.

This package is generated by ``scripts/gen_proto.sh`` from the vendored
``proto/ecosys/v1/ecosys.proto``. Do NOT hand-edit the generated modules.
"""
