# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ecosys.v1 import ecosys_pb2 as ecosys_dot_v1_dot_ecosys__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ecosys/v1/ecosys_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PairingServiceStub:
    """Pairing + liveness. Pair is the ONE rpc allowed without a bearer token
    (and only while a pairing window is open). Heartbeat requires a token.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Pair = channel.unary_unary(
                '/ecosys.v1.PairingService/Pair',
                request_serializer=ecosys_dot_v1_dot_ecosys__pb2.PairRequest.SerializeToString,
                response_deserializer=ecosys_dot_v1_dot_ecosys__pb2.PairResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/ecosys.v1.PairingService/Heartbeat',
                request_serializer=ecosys_dot_v1_dot_ecosys__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=ecosys_dot_v1_dot_ecosys__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class PairingServiceServicer:
    """Pairing + liveness. Pair is the ONE rpc allowed without a bearer token
    (and only while a pairing window is open). Heartbeat requires a token.
    """

    def Pair(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PairingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Pair': grpc.unary_unary_rpc_method_handler(
                    servicer.Pair,
                    request_deserializer=ecosys_dot_v1_dot_ecosys__pb2.PairRequest.FromString,
                    response_serializer=ecosys_dot_v1_dot_ecosys__pb2.PairResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=ecosys_dot_v1_dot_ecosys__pb2.HeartbeatRequest.FromString,
                    response_serializer=ecosys_dot_v1_dot_ecosys__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ecosys.v1.PairingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ecosys.v1.PairingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PairingService:
    """Pairing + liveness. Pair is the ONE rpc allowed without a bearer token
    (and only while a pairing window is open). Heartbeat requires a token.
    """

    @staticmethod
    def Pair(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecosys.v1.PairingService/Pair',
            ecosys_dot_v1_dot_ecosys__pb2.PairRequest.SerializeToString,
            ecosys_dot_v1_dot_ecosys__pb2.PairResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecosys.v1.PairingService/Heartbeat',
            ecosys_dot_v1_dot_ecosys__pb2.HeartbeatRequest.SerializeToString,
            ecosys_dot_v1_dot_ecosys__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class StreamServiceStub:
    """Bidirectional media + results relay. Every rpc here requires a token.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OpenStream = channel.stream_stream(
                '/ecosys.v1.StreamService/OpenStream',
                request_serializer=ecosys_dot_v1_dot_ecosys__pb2.StreamFrame.SerializeToString,
                response_deserializer=ecosys_dot_v1_dot_ecosys__pb2.StreamFrame.FromString,
                _registered_method=True)


class StreamServiceServicer:
    """Bidirectional media + results relay. Every rpc here requires a token.
    """

    def OpenStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OpenStream': grpc.stream_stream_rpc_method_handler(
                    servicer.OpenStream,
                    request_deserializer=ecosys_dot_v1_dot_ecosys__pb2.StreamFrame.FromString,
                    response_serializer=ecosys_dot_v1_dot_ecosys__pb2.StreamFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ecosys.v1.StreamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ecosys.v1.StreamService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StreamService:
    """Bidirectional media + results relay. Every rpc here requires a token.
    """

    @staticmethod
    def OpenStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ecosys.v1.StreamService/OpenStream',
            ecosys_dot_v1_dot_ecosys__pb2.StreamFrame.SerializeToString,
            ecosys_dot_v1_dot_ecosys__pb2.StreamFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
