# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ecosys/v1/ecosys.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ecosys/v1/ecosys.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x65\x63osys/v1/ecosys.proto\x12\tecosys.v1\"T\n\x0bPairRequest\x12\x0b\n\x03pin\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65vice_name\x18\x02 \x01(\t\x12#\n\x04role\x18\x03 \x01(\x0e\x32\x15.ecosys.v1.DeviceRole\"S\n\x0cPairResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\r\n\x05token\x18\x02 \x01(\t\x12\x11\n\tdevice_id\x18\x03 \x01(\t\x12\x15\n\rreject_reason\x18\x04 \x01(\t\"%\n\x10HeartbeatRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\"7\n\x11HeartbeatResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x16\n\x0eserver_time_ms\x18\x02 \x01(\x03\"K\n\x11StreamOpenRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12#\n\x04kind\x18\x02 \x01(\x0e\x32\x15.ecosys.v1.StreamKind\"C\n\x0cStreamResult\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x15\n\rspeaker_label\x18\x02 \x01(\t\x12\x0e\n\x06pts_ms\x18\x03 \x01(\x03\"\x8e\x01\n\x0bStreamFrame\x12\x19\n\x0f\x61udio_pcm16_16k\x18\x01 \x01(\x0cH\x00\x12\x18\n\x0evideo_h264_nal\x18\x02 \x01(\x0cH\x00\x12\x14\n\ntranscript\x18\x03 \x01(\tH\x00\x12)\n\x06result\x18\x04 \x01(\x0b\x32\x17.ecosys.v1.StreamResultH\x00\x42\t\n\x07payload*X\n\nDeviceRole\x12\x1b\n\x17\x44\x45VICE_ROLE_UNSPECIFIED\x10\x00\x12\x15\n\x11\x44\x45VICE_ROLE_GLASS\x10\x01\x12\x16\n\x12\x44\x45VICE_ROLE_DAEMON\x10\x02*W\n\nStreamKind\x12\x1b\n\x17STREAM_KIND_UNSPECIFIED\x10\x00\x12\x15\n\x11STREAM_KIND_AUDIO\x10\x01\x12\x15\n\x11STREAM_KIND_VIDEO\x10\x02\x32\x91\x01\n\x0ePairingService\x12\x37\n\x04Pair\x12\x16.ecosys.v1.PairRequest\x1a\x17.ecosys.v1.PairResponse\x12\x46\n\tHeartbeat\x12\x1b.ecosys.v1.HeartbeatRequest\x1a\x1c.ecosys.v1.HeartbeatResponse2Q\n\rStreamService\x12@\n\nOpenStream\x12\x16.ecosys.v1.StreamFrame\x1a\x16.ecosys.v1.StreamFrame(\x01\x30\x01\x42\x37P\x01Z3phone-manager/tools/mockpeer/gen/ecosys/v1;ecosysv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ecosys.v1.ecosys_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001Z3phone-manager/tools/mockpeer/gen/ecosys/v1;ecosysv1'
  _globals['_DEVICEROLE']._serialized_start=595
  _globals['_DEVICEROLE']._serialized_end=683
  _globals['_STREAMKIND']._serialized_start=685
  _globals['_STREAMKIND']._serialized_end=772
  _globals['_PAIRREQUEST']._serialized_start=37
  _globals['_PAIRREQUEST']._serialized_end=121
  _globals['_PAIRRESPONSE']._serialized_start=123
  _globals['_PAIRRESPONSE']._serialized_end=206
  _globals['_HEARTBEATREQUEST']._serialized_start=208
  _globals['_HEARTBEATREQUEST']._serialized_end=245
  _globals['_HEARTBEATRESPONSE']._serialized_start=247
  _globals['_HEARTBEATRESPONSE']._serialized_end=302
  _globals['_STREAMOPENREQUEST']._serialized_start=304
  _globals['_STREAMOPENREQUEST']._serialized_end=379
  _globals['_STREAMRESULT']._serialized_start=381
  _globals['_STREAMRESULT']._serialized_end=448
  _globals['_STREAMFRAME']._serialized_start=451
  _globals['_STREAMFRAME']._serialized_end=593
  _globals['_PAIRINGSERVICE']._serialized_start=775
  _globals['_PAIRINGSERVICE']._serialized_end=920
  _globals['_STREAMSERVICE']._serialized_start=922
  _globals['_STREAMSERVICE']._serialized_end=1003
# @@protoc_insertion_point(module_scope)
